FROM mcr.microsoft.com/windows/nanoserver:1809

COPY ./ziplinee-ci-builder.exe C:/ziplinee-ci-builder.exe
COPY ./templates C:/entrypoint-templates

ENV ZIPLINEE_CI_SERVER="ziplinee" \
    ZIPLINEE_WORKDIR="C:/ziplinee-work" \
    ZIPLINEE_LOG_FORMAT="v3"

USER ContainerAdministrator

WORKDIR ${ZIPLINEE_WORKDIR}

ENV DOCKER_API_VERSION 1.40

ENTRYPOINT ["C:/ziplinee-ci-builder.exe"]